version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  run_tests:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install npm dependencies
          command: |
            yarn --ignore-engines

      - run:
          name: Check eslint
          command: yarn eslint server

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    executor: heroku/default

    steps:
      - checkout
      - git pull origin dev
      - git pull origin master
      - heroku/install
      - heroku/deploy-via-git:
          branch: dev

workflows:
  heroku_deploy:
    jobs:
      - run_tests

      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - dev
